# Generated by Django 3.0.5 on 2026-06-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdischargedetails',
            name='symptoms',
            field=models.TextField(null=True),
        ),
    ]
